import { RadioBand, SimulatedStation } from '../types/radio';

export const RADIO_BANDS: RadioBand[] = [
  {
    id: 'fm_broadcast',
    name: 'FM Broadcast',
    shortName: 'FM 88-108',
    minFreqMHz: 87.5,
    maxFreqMHz: 108.0,
    defaultStepKHz: 200,
    defaultMode: 'WFM',
    defaultBandwidthHz: 180000,
    description: 'Commercial FM radio broadcast band (88 - 108 MHz). High fidelity stereo audio and RDS data.',
    category: 'broadcast',
  },
  {
    id: 'airband_vhf',
    name: 'Aviation Airband (VHF)',
    shortName: 'Airband 118-137',
    minFreqMHz: 118.0,
    maxFreqMHz: 137.0,
    defaultStepKHz: 25,
    defaultMode: 'AM',
    defaultBandwidthHz: 8330,
    description: 'Civil aviation communications between air traffic control (ATC), ground, towers, and aircraft.',
    category: 'aviation',
  },
  {
    id: 'marine_vhf',
    name: 'Marine VHF Radio',
    shortName: 'Marine 156-162',
    minFreqMHz: 156.0,
    maxFreqMHz: 162.05,
    defaultStepKHz: 25,
    defaultMode: 'NFM',
    defaultBandwidthHz: 12500,
    description: 'Maritime communications, ship-to-ship, bridge-to-bridge, port operations, and Coast Guard calling.',
    category: 'marine',
  },
  {
    id: 'noaa_weather',
    name: 'NOAA All-Hazards Weather',
    shortName: 'NOAA 162 MHz',
    minFreqMHz: 162.4,
    maxFreqMHz: 162.55,
    defaultStepKHz: 25,
    defaultMode: 'NFM',
    defaultBandwidthHz: 12500,
    description: 'National Oceanic and Atmospheric Administration automated 24/7 continuous weather broadcasts.',
    category: 'weather',
  },
  {
    id: 'ham_2m',
    name: '2-Meter Amateur Band',
    shortName: 'Ham 144-148',
    minFreqMHz: 144.0,
    maxFreqMHz: 148.0,
    defaultStepKHz: 20,
    defaultMode: 'NFM',
    defaultBandwidthHz: 12500,
    description: '144 - 148 MHz VHF amateur radio band. Repeater networks, simplex voice, CW, and digital packet modes.',
    category: 'amateur',
  },
  {
    id: 'ham_70cm',
    name: '70-Centimeter Amateur Band',
    shortName: 'Ham 430-440',
    minFreqMHz: 430.0,
    maxFreqMHz: 440.0,
    defaultStepKHz: 25,
    defaultMode: 'NFM',
    defaultBandwidthHz: 12500,
    description: '430 - 440 MHz UHF amateur radio band. High-coverage urban repeaters and satellite downlinks.',
    category: 'amateur',
  },
  {
    id: 'hf_shortwave',
    name: 'HF Shortwave / Time Standards',
    shortName: 'HF 10-15 MHz',
    minFreqMHz: 9.9,
    maxFreqMHz: 15.5,
    defaultStepKHz: 5,
    defaultMode: 'AM',
    defaultBandwidthHz: 6000,
    description: 'High-frequency shortwave broadcasts, WWV atomic clock time signals, and international DX.',
    category: 'shortwave',
  },
  {
    id: 'cb_radio',
    name: 'Citizens Band (CB 27 MHz)',
    shortName: 'CB 26-27 MHz',
    minFreqMHz: 26.965,
    maxFreqMHz: 27.405,
    defaultStepKHz: 10,
    defaultMode: 'AM',
    defaultBandwidthHz: 6000,
    description: '40-channel citizen band radio. Highway trucker chatter (Ch 19) and emergency channel 9.',
    category: 'util',
  },
];

export const SIMULATED_STATIONS: SimulatedStation[] = [
  // --- NOAA Weather Radio Channels ---
  {
    id: 'noaa_1',
    frequencyMHz: 162.400,
    name: 'NOAA KHB60 Station 1',
    category: 'weather',
    modulation: 'NFM',
    bandwidthKHz: 12.5,
    nominalPowerDbm: -48,
    dutyCycle: 1.0,
    cyclePeriodSec: 10,
    audioVoiceType: 'weather',
    description: 'Continuous coastal marine forecast, barometric pressure, wind advisories, and radar summary.',
  },
  {
    id: 'noaa_2',
    frequencyMHz: 162.475,
    name: 'NOAA WXM70 Station 2',
    category: 'weather',
    modulation: 'NFM',
    bandwidthKHz: 12.5,
    nominalPowerDbm: -55,
    dutyCycle: 1.0,
    cyclePeriodSec: 10,
    audioVoiceType: 'weather',
    description: 'Regional inland weather alerts, current temperature 68°F, dewpoint 52°F, barometric 30.12 inHg.',
  },
  {
    id: 'noaa_3',
    frequencyMHz: 162.550,
    name: 'NOAA KWO35 Station 3',
    category: 'weather',
    modulation: 'NFM',
    bandwidthKHz: 12.5,
    nominalPowerDbm: -62,
    dutyCycle: 1.0,
    cyclePeriodSec: 10,
    audioVoiceType: 'weather',
    description: 'Aviation terminal aerodrome forecasts (TAF) and high seas forecast.',
  },

  // --- Aviation Airband (118 - 137 MHz AM) ---
  {
    id: 'air_jfk_twr',
    frequencyMHz: 119.100,
    name: 'Metro Tower Control',
    category: 'aviation',
    modulation: 'AM',
    bandwidthKHz: 8.33,
    nominalPowerDbm: -52,
    dutyCycle: 0.65,
    cyclePeriodSec: 14,
    audioVoiceType: 'atc',
    description: 'Runway 28L/R arrivals and departures. "United 492 cleared for takeoff, wind 270 at 12 knots."',
  },
  {
    id: 'air_app_124',
    frequencyMHz: 124.350,
    name: 'Terminal Radar Approach',
    category: 'aviation',
    modulation: 'AM',
    bandwidthKHz: 8.33,
    nominalPowerDbm: -58,
    dutyCycle: 0.75,
    cyclePeriodSec: 12,
    audioVoiceType: 'atc',
    description: 'Vectors to final ILS approach. "Delta 816 turn left heading 210, descend and maintain 4000."',
  },
  {
    id: 'air_emerg_guard',
    frequencyMHz: 121.500,
    name: 'International Air Emergency Guard',
    category: 'aviation',
    modulation: 'AM',
    bandwidthKHz: 8.33,
    nominalPowerDbm: -70,
    dutyCycle: 0.25,
    cyclePeriodSec: 25,
    audioVoiceType: 'atc',
    description: 'Distress and urgency frequency monitored by all civil and military air traffic controllers.',
  },
  {
    id: 'air_ground_121_9',
    frequencyMHz: 121.900,
    name: 'International Airport Ground',
    category: 'aviation',
    modulation: 'AM',
    bandwidthKHz: 8.33,
    nominalPowerDbm: -64,
    dutyCycle: 0.55,
    cyclePeriodSec: 16,
    audioVoiceType: 'atc',
    description: 'Taxiway sequencing and gate pushback clearance. "FedEx 117 taxi to runway 04 via Alpha, Bravo."',
  },
  {
    id: 'air_atis_127_6',
    frequencyMHz: 127.600,
    name: 'Airport ATIS Information Kilo',
    category: 'aviation',
    modulation: 'AM',
    bandwidthKHz: 8.33,
    nominalPowerDbm: -50,
    dutyCycle: 1.0,
    cyclePeriodSec: 15,
    audioVoiceType: 'atc',
    description: 'Automated Terminal Information Service: "Sky condition clear, visibility 10 miles, altimeter 29.92."',
  },
  {
    id: 'air_center_132_4',
    frequencyMHz: 132.400,
    name: 'Enroute Sector Air Center',
    category: 'aviation',
    modulation: 'AM',
    bandwidthKHz: 8.33,
    nominalPowerDbm: -68,
    dutyCycle: 0.60,
    cyclePeriodSec: 18,
    audioVoiceType: 'atc',
    description: 'High altitude airway routing and flight level changes. "American 224 climb and maintain FL340."',
  },

  // --- FM Broadcast Band (88 - 108 MHz WFM) ---
  {
    id: 'fm_88_5',
    frequencyMHz: 88.500,
    name: '88.5 Jazz & Public Radio',
    category: 'broadcast',
    modulation: 'WFM',
    bandwidthKHz: 180,
    nominalPowerDbm: -42,
    dutyCycle: 1.0,
    cyclePeriodSec: 8,
    rds: {
      stationName: 'KJAZ-FM',
      radioText: 'Miles Davis - So What | 24/7 Pure Acoustic Jazz',
      programType: 'Jazz',
    },
    audioVoiceType: 'music',
    description: 'Non-commercial educational broadcaster transmitting 50 kW ERP from hilltop transmitter mast.',
  },
  {
    id: 'fm_90_3',
    frequencyMHz: 90.300,
    name: '90.3 Indie Soundwave',
    category: 'broadcast',
    modulation: 'WFM',
    bandwidthKHz: 180,
    nominalPowerDbm: -38,
    dutyCycle: 1.0,
    cyclePeriodSec: 8,
    rds: {
      stationName: 'KEXP-IND',
      radioText: 'Playing: The National - Bloodbuzz Ohio | Live in Studio',
      programType: 'Alternative',
    },
    audioVoiceType: 'music',
    description: 'Listener-supported independent arts radio with stereo pilot and dynamic RDS scrolling text.',
  },
  {
    id: 'fm_94_1',
    frequencyMHz: 94.100,
    name: '94.1 Classical Symphony',
    category: 'broadcast',
    modulation: 'WFM',
    bandwidthKHz: 180,
    nominalPowerDbm: -45,
    dutyCycle: 1.0,
    cyclePeriodSec: 8,
    rds: {
      stationName: 'WCRB-CL',
      radioText: 'Beethoven - Piano Concerto No. 5 "Emperor" Mov. 1',
      programType: 'Classical',
    },
    audioVoiceType: 'music',
    description: 'High dynamic range orchestral broadcasts with subcarrier SCA authorization.',
  },
  {
    id: 'fm_98_9',
    frequencyMHz: 98.900,
    name: '98.9 The Rock Pulse',
    category: 'broadcast',
    modulation: 'WFM',
    bandwidthKHz: 180,
    nominalPowerDbm: -35,
    dutyCycle: 1.0,
    cyclePeriodSec: 8,
    rds: {
      stationName: 'KROQ-ROC',
      radioText: 'Foo Fighters - Everlong | High Energy Rock',
      programType: 'Classic Rock',
    },
    audioVoiceType: 'music',
    description: '100 kW metropolitan commercial FM station with heavy audio compression & stereo subcarrier.',
  },
  {
    id: 'fm_103_7',
    frequencyMHz: 103.700,
    name: '103.7 Hot 40 Hits',
    category: 'broadcast',
    modulation: 'WFM',
    bandwidthKHz: 180,
    nominalPowerDbm: -40,
    dutyCycle: 1.0,
    cyclePeriodSec: 8,
    rds: {
      stationName: 'KHOT-TOP',
      radioText: 'Dua Lipa - Levitating | #1 Billboard Countdown',
      programType: 'Top 40',
    },
    audioVoiceType: 'music',
    description: 'Top 40 commercial hits broadcast with dense RDS radio text and traffic announcement flag.',
  },
  {
    id: 'fm_107_3',
    frequencyMHz: 107.300,
    name: '107.3 News / Talk Radio',
    category: 'broadcast',
    modulation: 'WFM',
    bandwidthKHz: 180,
    nominalPowerDbm: -46,
    dutyCycle: 1.0,
    cyclePeriodSec: 8,
    rds: {
      stationName: 'WNTK-TALK',
      radioText: 'National Headlines & Traffic on the 8s',
      programType: 'News/Talk',
    },
    audioVoiceType: 'music',
    description: 'Live news round-the-clock, sports commentary, and market reports.',
  },

  // --- Marine VHF Band (156 - 162 MHz NFM) ---
  {
    id: 'marine_ch16',
    frequencyMHz: 156.800,
    name: 'Marine VHF Ch 16 (Distress / Calling)',
    category: 'marine',
    modulation: 'NFM',
    bandwidthKHz: 12.5,
    nominalPowerDbm: -54,
    dutyCycle: 0.40,
    cyclePeriodSec: 20,
    audioVoiceType: 'chatter',
    description: 'International distress, safety, and calling channel. Coast Guard watchstanders listening 24/7.',
  },
  {
    id: 'marine_ch13',
    frequencyMHz: 156.650,
    name: 'Marine VHF Ch 13 (Bridge-to-Bridge)',
    category: 'marine',
    modulation: 'NFM',
    bandwidthKHz: 12.5,
    nominalPowerDbm: -63,
    dutyCycle: 0.30,
    cyclePeriodSec: 24,
    audioVoiceType: 'chatter',
    description: 'Navigation safety channel between vessels navigating in narrow channels and harbor tugboats.',
  },
  {
    id: 'marine_ch22a',
    frequencyMHz: 157.100,
    name: 'Marine VHF Ch 22A (Coast Guard Liaison)',
    category: 'marine',
    modulation: 'NFM',
    bandwidthKHz: 12.5,
    nominalPowerDbm: -59,
    dutyCycle: 0.35,
    cyclePeriodSec: 22,
    audioVoiceType: 'chatter',
    description: 'Maritime assistance, urgent marine information broadcasts, and notice to mariners.',
  },

  // --- 2-Meter Amateur Band (144 - 148 MHz) ---
  {
    id: 'ham_2m_simplex',
    frequencyMHz: 146.520,
    name: 'National 2m Simplex Calling',
    category: 'amateur',
    modulation: 'NFM',
    bandwidthKHz: 12.5,
    nominalPowerDbm: -58,
    dutyCycle: 0.50,
    cyclePeriodSec: 15,
    audioVoiceType: 'ssb_voice',
    description: 'Primary simplex calling frequency for North American amateur radio operators.',
  },
  {
    id: 'ham_2m_repeater_w7ai',
    frequencyMHz: 147.060,
    name: 'W7AI Mount Rainier Repeater',
    category: 'amateur',
    modulation: 'NFM',
    bandwidthKHz: 12.5,
    nominalPowerDbm: -47,
    dutyCycle: 0.60,
    cyclePeriodSec: 16,
    ctcssHz: 103.5,
    audioVoiceType: 'ssb_voice',
    description: 'High-elevation mountain repeater (+600 kHz offset, PL tone 103.5 Hz) covering 120-mile radius.',
  },
  {
    id: 'ham_2m_aprs',
    frequencyMHz: 144.390,
    name: 'APRS Digital Packet Beacon',
    category: 'amateur',
    modulation: 'NFM',
    bandwidthKHz: 12.5,
    nominalPowerDbm: -50,
    dutyCycle: 0.30,
    cyclePeriodSec: 8,
    audioVoiceType: 'cw',
    description: 'Automatic Packet Reporting System. 1200 baud Bell 202 AFSK GPS telemetry and weather packets.',
  },
  {
    id: 'ham_2m_cw_beacon',
    frequencyMHz: 144.275,
    name: 'W1AW/VHF Propagation Beacon',
    category: 'amateur',
    modulation: 'CW',
    bandwidthKHz: 0.5,
    nominalPowerDbm: -66,
    dutyCycle: 0.90,
    cyclePeriodSec: 10,
    morseText: 'CQ CQ CQ DE W1AW BCN FN31',
    audioVoiceType: 'cw',
    description: 'CW propagation beacon monitoring VHF tropospheric ducting and aurora openings.',
  },

  // --- 70-Centimeter Amateur Band (430 - 440 MHz) ---
  {
    id: 'ham_70cm_call',
    frequencyMHz: 446.000,
    name: '70cm National Simplex Calling',
    category: 'amateur',
    modulation: 'NFM',
    bandwidthKHz: 12.5,
    nominalPowerDbm: -60,
    dutyCycle: 0.40,
    cyclePeriodSec: 18,
    audioVoiceType: 'ssb_voice',
    description: 'National FM calling frequency for 70 cm band.',
  },
  {
    id: 'ham_70cm_dmr',
    frequencyMHz: 444.100,
    name: 'Metropolitan DMR Repeater',
    category: 'amateur',
    modulation: 'NFM',
    bandwidthKHz: 12.5,
    nominalPowerDbm: -53,
    dutyCycle: 0.55,
    cyclePeriodSec: 14,
    audioVoiceType: 'chatter',
    description: 'Tier II Digital Mobile Radio (DMR) repeater linked to BrandMeister network worldwide.',
  },

  // --- HF Shortwave / Time Standards ---
  {
    id: 'hf_wwv_10',
    frequencyMHz: 10.000,
    name: 'WWV Atomic Clock Time Station (10 MHz)',
    category: 'shortwave',
    modulation: 'AM',
    bandwidthKHz: 6.0,
    nominalPowerDbm: -56,
    dutyCycle: 1.0,
    cyclePeriodSec: 10,
    audioVoiceType: 'time_signal',
    description: 'NIST Fort Collins, CO time station. Second ticks, UT1 corrections, and Greenwich time announcement.',
  },
  {
    id: 'hf_chu_time',
    frequencyMHz: 14.670,
    name: 'CHU Canada Time Signal',
    category: 'shortwave',
    modulation: 'USB',
    bandwidthKHz: 3.0,
    nominalPowerDbm: -64,
    dutyCycle: 1.0,
    cyclePeriodSec: 10,
    audioVoiceType: 'time_signal',
    description: 'National Research Council Canada standard time and frequency broadcast in French and English.',
  },
  {
    id: 'hf_ft8_20m',
    frequencyMHz: 14.074,
    name: '20m FT8 Weak Signal Digital',
    category: 'shortwave',
    modulation: 'USB',
    bandwidthKHz: 3.0,
    nominalPowerDbm: -62,
    dutyCycle: 0.85,
    cyclePeriodSec: 15,
    audioVoiceType: 'cw',
    description: '8-GFSK digital protocol for weak-signal DX communications synchronized to exact 15-second cycles.',
  },

  // --- Citizens Band (27 MHz) ---
  {
    id: 'cb_ch19',
    frequencyMHz: 27.185,
    name: 'CB Channel 19 (Highway Truckers)',
    category: 'util',
    modulation: 'AM',
    bandwidthKHz: 6.0,
    nominalPowerDbm: -58,
    dutyCycle: 0.65,
    cyclePeriodSec: 12,
    audioVoiceType: 'chatter',
    description: 'North American highway travel channel. Road conditions, speed traps, and commercial haulers.',
  },
  {
    id: 'cb_ch9',
    frequencyMHz: 27.065,
    name: 'CB Channel 9 (Emergency Assistance)',
    category: 'util',
    modulation: 'AM',
    bandwidthKHz: 6.0,
    nominalPowerDbm: -72,
    dutyCycle: 0.20,
    cyclePeriodSec: 30,
    audioVoiceType: 'chatter',
    description: 'Dedicated emergency assistance channel monitored by REACT and volunteer safety patrols.',
  },
];
